"""
Signal weight manager (v29 Feature #14) — Auto-adjusting signal weights.

Tracks rolling per-signal accuracy from cycle_signals + trade outcomes.
Adjusts weights based on recent performance:
  - Accuracy < 40% → halve weight
  - Accuracy > 60% → increase 25% (cap at SIGNAL_WEIGHT_MAX)
  - Minimum weight: SIGNAL_WEIGHT_MIN (never fully disable)

Persists weights to signal_weights.json for visibility and override.
"""

from __future__ import annotations

import json
import logging
import sqlite3
import time
from pathlib import Path
from typing import Dict, Optional

from bot_config import CFG

logger = logging.getLogger("signal_weights")

WEIGHT_FILE = Path("signal_weights.json")

# Default weights — these are the baseline multipliers for each signal
# in calc_signal_confluence(). 1.0 = no adjustment.
DEFAULT_WEIGHTS: Dict[str, float] = {
    "fractal": 1.0,
    "sweep": 1.0,
    "mtf": 1.0,
    "opening": 1.0,
    "delta_levels": 1.0,
    "key_level": 1.0,
    "vwap_reversion": 1.0,
    "bond_leadlag": 1.0,
    "vix9d": 1.0,
    "fedwatch": 1.0,
}


class SignalWeightManager:
    """
    Manages adaptive signal weights based on rolling accuracy.

    Usage:
        swm = SignalWeightManager(journal_db_path)
        weights = swm.get_weights()  # pass to calc_signal_confluence()
        swm.update_weights()         # call hourly to recalculate
    """

    def __init__(self, journal_db_path: Path = CFG.DB_FILE,
                 signal_db_path: Path = Path("signal_logger.db")):
        self.journal_db = journal_db_path
        self.signal_db = signal_db_path
        self.weights = self._load_weights()
        self._last_update = 0.0

    def _load_weights(self) -> Dict[str, float]:
        """Load weights from file, falling back to defaults."""
        if WEIGHT_FILE.exists():
            try:
                data = json.loads(WEIGHT_FILE.read_text())
                weights = dict(DEFAULT_WEIGHTS)
                weights.update(data.get("weights", {}))
                return weights
            except (json.JSONDecodeError, KeyError):
                pass
        return dict(DEFAULT_WEIGHTS)

    def _save_weights(self):
        """Persist current weights to JSON file."""
        data = {
            "weights": self.weights,
            "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            "note": "Auto-generated by SignalWeightManager. Edit to override.",
        }
        WEIGHT_FILE.write_text(json.dumps(data, indent=2))

    def get_weights(self) -> Dict[str, float]:
        """Return current weights dict for use in calc_signal_confluence()."""
        if not CFG.SIGNAL_DECAY_ENABLED:
            return dict(DEFAULT_WEIGHTS)
        return dict(self.weights)

    def compute_rolling_accuracy(self, days: int = None) -> Dict[str, dict]:
        """
        Compute per-signal rolling accuracy from cycle_signals + trades.

        For each signal, finds cycles where it voted directionally,
        then checks if the corresponding trade (if taken) was a win or loss.

        Returns: {signal_name: {"trades": N, "wins": N, "accuracy": float}}
        """
        if days is None:
            days = CFG.SIGNAL_DECAY_LOOKBACK_DAYS

        results = {}
        try:
            with sqlite3.connect(self.signal_db) as sconn:
                sconn.row_factory = sqlite3.Row
                cutoff = f"datetime('now', '-{days} days')"

                # Get cycles that led to trades
                rows = sconn.execute(f"""
                    SELECT
                        fractal_dir, fractal_conf, mtf_alignment,
                        confluence_level, confluence_bull_score, confluence_bear_score,
                        vix9d_ratio, final_verdict, trade_taken, trade_id
                    FROM cycle_signals
                    WHERE timestamp >= {cutoff}
                      AND trade_taken = 1
                      AND trade_id IS NOT NULL
                """).fetchall()

            if not rows:
                return results

            # Get trade outcomes
            trade_ids = [r["trade_id"] for r in rows if r["trade_id"]]
            if not trade_ids:
                return results

            with sqlite3.connect(self.journal_db) as jconn:
                jconn.row_factory = sqlite3.Row
                placeholders = ",".join("?" * len(trade_ids))
                trade_rows = jconn.execute(f"""
                    SELECT id, status, pnl, verdict FROM trades
                    WHERE id IN ({placeholders})
                """, trade_ids).fetchall()

            trade_outcomes = {r["id"]: dict(r) for r in trade_rows}

            # Score each signal
            signal_stats = {name: {"trades": 0, "wins": 0} for name in DEFAULT_WEIGHTS}

            for cycle in rows:
                tid = cycle["trade_id"]
                outcome = trade_outcomes.get(tid)
                if not outcome:
                    continue
                is_win = outcome["status"] == "WIN"

                # Fractal: voted if conf >= 65
                if (cycle["fractal_conf"] or 0) >= 65:
                    signal_stats["fractal"]["trades"] += 1
                    if is_win:
                        signal_stats["fractal"]["wins"] += 1

                # MTF: voted if alignment contains BULL or BEAR
                mtf_al = cycle["mtf_alignment"] or ""
                if "BULL" in mtf_al or "BEAR" in mtf_al:
                    signal_stats["mtf"]["trades"] += 1
                    if is_win:
                        signal_stats["mtf"]["wins"] += 1

                # Confluence: if bull or bear score > 0
                bull_s = cycle["confluence_bull_score"] or 0
                bear_s = cycle["confluence_bear_score"] or 0
                if bull_s > 3 or bear_s > 3:
                    # Strong confluence signals were present
                    for name in ["vwap_reversion", "bond_leadlag", "key_level",
                                 "delta_levels", "opening", "sweep"]:
                        signal_stats[name]["trades"] += 1
                        if is_win:
                            signal_stats[name]["wins"] += 1

                # VIX9D: if ratio available
                if cycle["vix9d_ratio"] and cycle["vix9d_ratio"] != 1.0:
                    signal_stats["vix9d"]["trades"] += 1
                    if is_win:
                        signal_stats["vix9d"]["wins"] += 1

            # Compute accuracy
            for name, stats in signal_stats.items():
                if stats["trades"] >= 5:  # minimum sample
                    stats["accuracy"] = stats["wins"] / stats["trades"]
                else:
                    stats["accuracy"] = 0.5  # not enough data, neutral
                results[name] = stats

        except Exception as e:
            logger.warning(f"compute_rolling_accuracy failed: {e}")

        return results

    def update_weights(self) -> Dict[str, float]:
        """
        Recalculate and apply weight adjustments based on rolling accuracy.

        Returns dict of {signal: new_weight} for any changed weights.
        """
        if not CFG.SIGNAL_DECAY_ENABLED:
            return {}

        accuracy = self.compute_rolling_accuracy()
        if not accuracy:
            return {}

        changes = {}
        for name, stats in accuracy.items():
            if stats["trades"] < 5:
                continue  # not enough data

            current = self.weights.get(name, 1.0)
            acc = stats["accuracy"]

            if acc < 0.40:
                # Poor accuracy — halve weight
                new_weight = max(CFG.SIGNAL_WEIGHT_MIN, current * 0.5)
            elif acc > 0.60:
                # Good accuracy — increase 25%
                new_weight = min(CFG.SIGNAL_WEIGHT_MAX, current * 1.25)
            else:
                # Neutral — drift toward 1.0
                new_weight = current + (1.0 - current) * 0.1

            new_weight = round(new_weight, 3)
            if abs(new_weight - current) > 0.01:
                self.weights[name] = new_weight
                changes[name] = new_weight
                logger.info(
                    f"[SIGNAL DECAY] {name}: {current:.3f} -> {new_weight:.3f} "
                    f"(accuracy {acc:.0%} over {stats['trades']} trades)"
                )

        if changes:
            self._save_weights()
            self._last_update = time.time()

        return changes

    def apply_feedback_adjustment(self, signal_name: str, direction: str,
                                  max_change: float = None):
        """
        Apply a weight adjustment from post-trade review feedback (Feature #13).

        direction: "increase" or "decrease"
        max_change: maximum weight change (defaults to FEEDBACK_MAX_WEIGHT_CHANGE)
        """
        if max_change is None:
            max_change = CFG.FEEDBACK_MAX_WEIGHT_CHANGE

        current = self.weights.get(signal_name, 1.0)

        if direction == "increase":
            new_weight = min(CFG.SIGNAL_WEIGHT_MAX, current + max_change)
        elif direction == "decrease":
            new_weight = max(CFG.SIGNAL_WEIGHT_MIN, current - max_change)
        else:
            return

        self.weights[signal_name] = round(new_weight, 3)
        self._save_weights()
        logger.info(
            f"[FEEDBACK] {signal_name}: {current:.3f} -> {new_weight:.3f} ({direction})"
        )
